services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: meet_team
      MYSQL_PASSWORD: meet_team
      MYSQL_DATABASE: meet_team
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - meet_team_mysql:/var/lib/mysql
volumes:
  meet_team_mysql:

# link from localhost: mysql -h 127.0.0.1 -P 3306 -u meet_team -p
